server:
  port: 9000

spring:
  application.name: polyclinic
  datasource:
    url: jdbc:postgresql://localhost:5432/polyclinic
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true